name: Build and Test Maven Project with Docker with Production Tag

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK (for Maven)
      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      # Step 3: Install Maven
      - name: Set up Maven
        run: |
          sudo apt-get install -y maven

      # Step 4: Cache Maven dependencies (optional but helps with faster builds)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Validate the Maven project (check for any errors)
      - name: Validate Maven Project
        run: mvn clean verify -DskipTests=true

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build, tag, and push Docker image using Makefile
      - name: Build and push Docker image using Makefile
        env:
          REGISTRY: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: make docker-build-push-dev
